spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(Jyjwf0Py5i+1Oj8yVdb+yMJTMJ6N1/q8UWwujtSaJKA0vwRTt+SxhXCIhsSrGnAACaQR13tkU5wWBYSEQ+u3dtjSKM4FBqzzqq+Af49G2hzOv3s41CC9n3P1bC2HVDKTIVvakg4qXlON9RcIFZFw6c53tC+l1gvEfatAs1pbNNjQ+MWePjO9slWGvWw/rmdBKT6jIN2waMg=)
    username: ENC(3ybLNQX1PVxGR9q4B2F6hicdrJSyxLmc)
    password: ENC(jVyVMoKLp8tEN2HonLx5vwUeoFpA2gco)

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

aws:
  s3:
    region: ENC(g5tyuGOJBDEmnezuqqberSvKxUO3sHtm)
    bucket: ENC(xV+R4mKu3wiOHGoDKhWrsRyXTDOauoNy)

jwt:
  secret: ENC(m8hv7okIea5oHi2vzsdKBKl4Pzbv8fFW3cU1UVWrk4a7IWTmyVl27pUqqyhP/Ril2V4Vpyv4nObk6lojgwnZag==)
