spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(Zz2JN+QxyoZbD4ttf/rEC5JBBlvCakU/jwL7ui4Q4YINlLnsRHLi+QlcI317pZfpdqTM0eMMsJujpF/nCPBV8JQUghg+uDv/7EmtcCwao3irxw0EpYyTCVOCqY29Wgu1uhmZNtvcKAecr2fmTKKpvjcyyMv6w7TQBSON8NahXEJc6O41814ZTQDVS4TS/JeODFOdc8DJHZk=)
    username: ENC(OjA8rVEi00HMuuS1y/PRWwSfhuxQFhqB)
    password: ENC(ZcAq+WByuDAqTlHsJRSemYcNaEwlFRp9)

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

aws:
  s3:
    region: ENC(AVCMaqBKtI5yHdJHx9XNjik58YlUD/EY)
    bucket: ENC(lv1CzlIwi9jUaOJJth3Ppf73A1VpIoRb)

jwt:
  secret: ENC(m8hv7okIea5oHi2vzsdKBKl4Pzbv8fFW3cU1UVWrk4a7IWTmyVl27pUqqyhP/Ril2V4Vpyv4nObk6lojgwnZag==)

