spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(Jyjwf0Py5i+1Oj8yVdb+yMJTMJ6N1/q8UWwujtSaJKA0vwRTt+SxhXCIhsSrGnAACaQR13tkU5wWBYSEQ+u3dtjSKM4FBqzzqq+Af49G2hzOv3s41CC9n3P1bC2HVDKTIVvakg4qXlON9RcIFZFw6c53tC+l1gvEfatAs1pbNNjQ+MWePjO9slWGvWw/rmdBKT6jIN2waMg=)
    username: ENC(3ybLNQX1PVxGR9q4B2F6hicdrJSyxLmc)
    password: ENC(jVyVMoKLp8tEN2HonLx5vwUeoFpA2gco)

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
  archiving:
    url: ENC(mgbO6QO3wScbYH9yPV/a7e5cvA6sc5/z9dig4/VlywgHXN+UrDaRWhQYOAY7bqEkcI8O2nmMlWIIUlzZyaRzSoD+AmgSVeQUPNCcYGPt1B1dZHbtNCZmc5i6KWBJfKKx)
  servlet:
    context-path: /api

jwt:
  secret: ENC(7JHqgwmXfXySGksMK5SOUrWg7edAhDXA044D8pyPbQbsYgdgs+by47ti/tHUwlwqSCMmmD9FM3tZvazmb/0wtqTKqYXGsrNnlkD2yFO11Z6Gis49IO0SWhaAnmyUexlwy+Bscc2pZBK12M50vCeHkFQGRIe1SlPj)

aws:
  s3:
    region: ENC(g5tyuGOJBDEmnezuqqberSvKxUO3sHtm)
    bucket: ENC(xV+R4mKu3wiOHGoDKhWrsRyXTDOauoNy)

redis:
  host: ENC(wIh6kiQ7W/qgHC1zR1Vb7ZanSpzgLsT7)
  port: ENC(52XQ9OWXFVilIpOWtV217g==)
  password: ENC(12sPod7cSJbwOScRscRp3A==)
