spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(mSvjwh9XzRQ6xRcA3rKI6KXZWShDbjv2W45e3zKurxFjRmk+Xc/yw6tyDryXLEZ1z8bDU6AYZlXOlXnx0jw87UYH4l3XG/EwMWzRMTG/ttKoG33q4rj7YoYTHhMNyuzrPawfMVuLW1L3N33jsSctrDG3BcSOgVvN1e5t8kVhhkO2k2UudJjH8NqA6giZdahcIJjAeNSp+zg=)
    username: ENC(3ybLNQX1PVxGR9q4B2F6hicdrJSyxLmc)
    password: ENC(jVyVMoKLp8tEN2HonLx5vwUeoFpA2gco)

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
